# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0088131052f08844fc72b3b8009bbf431b3367370dce850dd6c2c18cfa81393a5ca5862e14439ddaa562f0d52f75485fcd80b80caf30bd561ff8a0ab3b68fb54

test:
  secret_key_base: 9e45c45c84b360e49771864cf299b02ae82386c53fc6c0b8a1dc81f6caf74211ac3c855b2de314fec94d02001fc09cf0cec717a6b64d96f7cdbc9113e1097d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
